### ISSUE TITLE
Default options for selecting industries

### ISSUE THREAD

**Issue by bradentam** [UBC-MDS/DSCI532_Group112_Unemployment_DashR#12]
Hey team!!!

I think we should update the default options for selecting industries so that we only include "Agriculture" and "Construction". Having all the industries show up immediately may be overwhelming for the user and it's a very messy plot. 

Let me know what you guys think!!!

Best,
Braden

**Comment by carlinakim** [comment]
Hey Braden!

I appreciate your insight and I think that is a good idea! We should incorporate that into our app. I will make sure this issue is fixed before deployment.

All the best, 
Carlina

**Comment by marvinmin** [comment]
Changed
